## -------------------------- ##
# Values to override for your instance.
## -------------------------- ##

## An option to override the atlantis url,
##   if not using an ingress, set it to the external IP.
# atlantisUrl: http://10.0.0.0

# Replace this with your own repo whitelist:
orgWhitelist: "github.com/<user-or-organization>/*"

## Use Server Side Repo Config,
## ref: https://www.runatlantis.io/docs/server-side-repo-config.html
## Example default configuration
repoConfig: |
  ---
  repos:
  - id: /.*/
  apply_requirements: [approved, mergeable]
  workflow: default
  workflows:
    default:
      plan:
        steps: [init, plan]
      apply:
        steps: [apply]

## defaultTFVersion set the default terraform version to be used in atlantis server
defaultTFVersion: 0.12.26

# If using GitHub, specify like the following:
github:
  user: user
  token: token
  secret: secret

# To specify AWS credentials to be mapped to ~/.aws:
aws:
  credentials: |
    [default]
    aws_access_key_id=id
    aws_secret_access_key=access_key
    region=eu-west-1

  config: |
    [default]
    source_profile = default
# To reference an already existing Secret object with AWS credentials
# awsSecretName: 'mysecretwithawscreds'

# allowForkPRs enables atlantis to run on a fork Pull Requests
allowForkPRs: false

# disableApplyAll disables running `atlantis apply` without any flags
disableApplyAll: false

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  host: chart-example.local

resources:
  requests:
    memory: 1Gi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 100m

# Disk space for Atlantis to check out repositories
dataStorage: 1Gi

replicaCount: 1

## test container details
test:
  enabled: false
